### ISSUE TITLE
[BUGFIX] Catching uncaught exceptions and send error message to user

### ISSUE THREAD

**Issue by Dragonsight91** [Dragonsight91/Demon-Overlord#67]
**Describe the bug**

**To Reproduce**

1. use `-mao {any interaction} {any mention} {fill the message with some character}`

**Expected behavior**
The bot should print an error but no traceback to the console and give an error to the user

**Screenshots**
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/bot/DemonOverlord/core/demonoverlord.py", line 262, in on_message
    await command.exec()
  File "/bot/DemonOverlord/core/util/command.py", line 117, in exec
    message = await self.channel.send(embed=response, reference=self.reference)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 935, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
```

**Comment by Natshirt** [comment]
I will try to fix this bug

**Comment by Dragonsight91** [comment]
> I will try to fix this bug

it's all yours
